image: docker:git
services:
- docker:dind

stages:
- build
# - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $IMAGE_TAG || true
    - docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# disabled test for now
.test:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests
