---
sudo: required
language: node_js
services: docker
node_js: 
  - "10"
before_install: 
  - "npm i -g npm@v6.0.1"
cache: 
  - 
    directories: 
      - node_modules
install: 
  - "npm install"

script: 
  - "npm run test"
deploy:
  - docker build -t lovethebomb/data-tiles .
